"""empty message

Revision ID: 479a2fb3565b
Revises: 66026879e578
Create Date: 2018-09-18 23:40:02.957708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479a2fb3565b'
down_revision = '66026879e578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_activity', 'timestamp')
    # ### end Alembic commands ###
