"""userActivity added

Revision ID: 66026879e578
Revises: 11c5977d3a44
Create Date: 2018-09-09 22:52:50.012860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66026879e578'
down_revision = '11c5977d3a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventName', sa.String(length=32), nullable=True),
    sa.Column('parameter', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activity')
    # ### end Alembic commands ###
